spice_mix = set()
print(f"Initial spice mix id: {id(spice_mix)}")
print(f"Initial spice mix : {spice_mix}")
spice_mix.add("Ginger")
spice_mix.add("Cardmon")
print(f"After spice mix id: {id(spice_mix)}")
print(f"after spice mix : {spice_mix}")